-- DECLARE CURSOR --
DECLARE 
  CURSOR DATACURSOR IS SELECT * FROM DATASTREAM;
  TYPE V_DATACURSOR IS TABLE OF DATACURSOR%ROWTYPE;
  T_ID V_DATACURSOR;
  
/* CREATE VARIABLES TO STORE MASTERDATA */
  VPRODUCT_ID      MASTERDATA.PRODUCT_ID%TYPE;
  VPRODUCT_NAME    MASTERDATA.PRODUCT_NAME%TYPE;
  VSUPPLIER_ID     MASTERDATA.SUPPLIER_ID%TYPE;
  VSUPPLIER_NAME   MASTERDATA.SUPPLIER_NAME%TYPE;
  VPRICE           MASTERDATA.SALE_PRICE%TYPE;

REC INT; /* Temporary variable for checking duplicates */ 

-- EXTRACTION --
BEGIN
OPEN DATACURSOR;
LOOP
  FETCH DATACURSOR BULK COLLECT INTO T_ID LIMIT 100;
  EXIT WHEN DATACURSOR%NOTFOUND;
  
  FOR i IN T_ID.FIRST .. T_ID.LAST
    LOOP
    
  SELECT PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, SUPPLIER_NAME, SALE_PRICE 
         INTO VPRODUCT_ID, VPRODUCT_NAME, VSUPPLIER_ID, VSUPPLIER_NAME, VPRICE
         FROM MASTERDATA WHERE PRODUCT_ID = T_ID(i).PRODUCT_ID;
   
         
/* CHECK IF DIMENSION TABLE HAS RECORD. IF YES THEN UPATE TO FACT TABLE. ELSE UPATE FOR ALL.*/

-- CUSTOMER DIMENSION --
SELECT COUNT(0) INTO REC FROM CUSTOMER
       WHERE CUSTOMER_ID = T_ID(i).CUSTOMER_ID;
   IF REC=0 THEN
      INSERT INTO CUSTOMER(CUSTOMER_ID,CUSTOMER_NAME)
      VALUES(T_ID(i).CUSTOMER_ID,T_ID(i).CUSTOMER_NAME);
END IF;

-- WAREHOUSE DIMENSION --
SELECT COUNT(0) INTO REC FROM WAREHOUSE
       WHERE WAREHOUSE_ID = T_ID(i).WAREHOUSE_ID;
    IF REC=0 THEN
       INSERT INTO WAREHOUSE(WAREHOUSE_ID,WAREHOUSE_NAME)
       VALUES(T_ID(i).WAREHOUSE_ID,T_ID(i).WAREHOUSE_NAME);
END IF;

-- PRODUCT DIMENSION --
SELECT COUNT(0) INTO REC FROM PRODUCT
       WHERE PRODUCT_ID = T_ID(i).PRODUCT_ID;
    IF REC=0 THEN
       INSERT INTO PRODUCT(PRODUCT_ID,PRODUCT_NAME,SALE_PRICE)
       VALUES(T_ID(i).PRODUCT_ID, VPRODUCT_NAME, VPRICE);
END IF;

-- SUPPLIER DIMENSION --
SELECT COUNT(0) INTO REC FROM SUPPLIER
       WHERE SUPPLIER_ID = VSUPPLIER_ID;
    IF REC =0 THEN
       INSERT INTO SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME)
       VALUES(VSUPPLIER_ID,VSUPPLIER_NAME);
END IF;

-- TIME DIMENSION --
SELECT COUNT(0) INTO REC FROM DDATE WHERE TIME_ID = T_ID(i).T_DATE;
     IF REC=0 THEN
        INSERT INTO DDATE (TIME_ID, T_DATE, T_YEAR,T_QUARTER,T_MONTH,T_DAY)
        VALUES(TO_CHAR(T_ID(i).T_DATE,'DDMMYYYY'), T_ID(i).T_DATE,
        EXTRACT(YEAR FROM T_ID(i).T_DATE), TO_CHAR(T_ID(i).T_DATE,'Q'),
        EXTRACT(MONTH FROM T_ID(i).T_DATE),
        EXTRACT(DAY FROM T_ID(i).T_DATE));
END IF;

-- FACT SALES --
SELECT COUNT(0) INTO REC FROM SALES
       WHERE DATASTREAM_ID = T_ID(i).DATASTREAM_ID;
    IF REC=0 THEN
       INSERT INTO SALES(DATASTREAM_ID, CUSTOMER_ID, PRODUCT_ID,WAREHOUSE_ID,
                         SUPPLIER_ID,T_DATE,TOTAL_SALE,QUANTITY_SOLD)
       VALUES(T_ID(i).DATASTREAM_ID,T_ID(i).CUSTOMER_ID,T_ID(i).PRODUCT_ID,
              T_ID(i).WAREHOUSE_ID,VSUPPLIER_ID,T_ID(i).T_DATE,
              T_ID(i).QUANTITY_SOLD*VPRICE, T_ID(i).QUANTITY_SOLD);
    END IF;
    COMMIT;
  END LOOP;
  COMMIT;
END LOOP;
CLOSE DATACURSOR;
END;


